# this is a sample action to learn workflow dispatch which is used when the action is run manually.
name:  create-sample-ticket
on : 
  workflow_dispatch:
    inputs:
      title: "Create tickets"  
        description : "Issue title"
        required: true
      body: 
        description : "Issue body"
        required: true
      
